spring:
  application:
    名字: adg-rule
  profiles:
    已激活: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  rule:
    #远程规则
    remote:
      # - 'https://cdn.jsdelivr.net/gh/hoshsadiq/adblock-nocoin-list/hosts.txt'  #adblock-nocoin-list
      # - 'https://cdn.jsdelivr.net/gh/durablenapkin/scamblocklist/adguard.txt' #Scam Blocklist
      # - 'https://someonewhocares.org/hosts/zero/hosts' #Dan Pollock's List
      # #- 'https://cdn.jsdelivr.net/gh/AdguardTeam/FiltersRegistry/filters/filter_15_DnsFilter/filter.txt' #AdGuard DNS filter
      # - 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext' #Peter Lowe's List
      # - 'https://abp.oisd.nl/basic/' #OISD Blocklist Basic
      # #- 'https://adaway.org/hosts.txt' #AdAway Default Blocklist
      # - 'https://cdn.jsdelivr.net/gh/crazy-max/WindowsSpyBlocker/data/hosts/spy.txt' #WindowsSpyBlocker
      # #- 'https://cdn.jsdelivr.net/gh/o0HalfLife0o/list@master/ad-pc.txt' #HalfLife（pc）
      # #- 'https://cdn.jsdelivr.net/gh/banbendalao/ADgk@master/ADgk.txt' #Adgk
      # #- 'https://cdn.jsdelivr.net/gh/VeleSila/yhosts/hosts.txt' #yhosts
      # - 'https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts' #大圣净化
      # #- 'https://gitlab.com/quidsup/notrack-blocklists/-/raw/master/trackers.list' #Domains classified as tracking or advertising
      # - 'https://code.gitlink.org.cn/hacamer/AdRules/raw/branch/main/adguard-full.txt' #AdRules AdGuard Full List
      # - 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt' #adguard base
      # #自用添加↓
      # - 'https://anti-ad.net/easylist.txt' #name: anti-AD
      # #- 'https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts' #name: StevenBlack/hosts规则
      # - 'https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/combined_disguised_trackers.txt' #name: AdGuard CNAME 伪装跟踪器列表
      # - 'https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt' #name: AdGuard DNS filter
      # - 'https://raw.githubusercontent.com/Crystal-RainSlide/AdditionalFiltersCN/master/CN.txt' #name: AdditionalFiltersCN
      # - 'https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt' #name: ADgk 移动广告规则
      # - 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt' #name: 乘风 广告过滤规则
      # - 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt' #name: 乘风 视频过滤规则
      # - 'https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad.txt' #name: HalfLife_合并自乘风视频广告过滤规则、EasylistChina、EasylistLite、CJX'sAnnoyance
      # - 'https://adaway.org/hosts.txt' #name: AdAway 官方的去广告 Host 规则
      # - 'https://easylist-downloads.adblockplus.org/antiadblockfilters.txt' #name: 去除禁止广告拦截提示规则
      # #- 'https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts.txt' #name: Yhosts规则
      # #- 'https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts' #name: 大圣净化（针对国内视频）
      # #- 'https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-YouTube-AdBlock-Filter.txt' #name: GoodbyeAds-YouTube
      # #- 'https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-AdBlock-Filter.txt' #name: GoodbyeAds
      # #- 'https://www.trli.club/ad-hosts/ad-hosts-sqlist/ad-adguardhome-dnstype.txt' #name: 冷莫(trli)AdHosts-Sqlist
      # #- 'https://file.trli.club:2087/ad-youtube-hosts/ad-youtube-adguardhome-dnstype.txt' #name: 冷莫(trli)Ad-YouTuBe-Hosts
      # - 'https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt' #name: 杏稍AdRules DNS List
      # - 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/AdGuard/Advertising/Advertising.txt' #name: AdGuard_blackmatrix7合并
      # - 'https://raw.githubusercontent.com/zsakvo/AdGuard-Custom-Rule/master/rule/zhihu.txt' #name: 知乎 普通版
      # #- 'https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockfilters.txt' #name: 217heidai/adblockfilters去重合并(比较大)
      # - 'https://raw.githubusercontents.com/timlu85/AdGuard-Home_Youtube-Adfilter/master/Youtube-Adfilter-Web.txt' #name: Youtube-Adfilter-Web
      # - 'https://raw.githubusercontents.com/91ajames/ublock-filters-ulist-youtube/main/blocklist.txt' #name: ublock-filters-ulist-youtube
      # #KoolProxy规则
      # #- 'https://raw.iqiq.io/ilxp/koolproxy/master/rules/koolproxy.txt' #name:静态白名单规则
      # - 'https://raw.iqiq.io/ilxp/koolproxy/master/rules/daily.txt' #name:每日规则
      # #- 'https://raw.iqiq.io/ilxp/koolproxy/master/rules/adg.txt' #name:AdGuard规则
      # #- 'https://raw.iqiq.io/ilxp/koolproxy/master/rules/adgk.txt' #name:Banben规则
      # #- 'https://raw.iqiq.io/ilxp/koolproxy/master/rules/yhosts.txt' #name:Yhosts规则
      # - 'https://raw.iqiq.io/ilxp/koolproxy/master/rules/steven.txt' #name:StevenBlack规则
      # #uBlock内置规则
      # - 'https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/filters/filters.txt' #name: uBlock filters
      # - 'https://ublockorigin.pages.dev/filters/badware.txt' #name: uBlock filters – Badware risks
      # - 'https://gitcdn.link/cdn/uBlockOrigin/uAssetsCDN/main/filters/privacy.txt' #name: uBlock filters – Privacy
      # - 'https://ublockorigin.github.io/uAssets/filters/quick-fixes.txt' #name: uBlock filters – Quick fixes
      # - 'https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/filters/resource-abuse.txt' #name: uBlock filters – Resource abuse
      # - 'https://gitcdn.link/cdn/uBlockOrigin/uAssetsCDN/main/filters/unbreak.txt' #name: uBlock filters – Unbreak
      # - 'https://filters.adtidy.org/extension/ublock/filters/11.txt' #name: AdGuard Mobile Ads移动设备
      - 'https://raw.githubusercontent.com/hululu1068/AdGuard-Rule/main/rule/all.txt'
      - 'https://o0.pages.dev/Lite/adblock.txt'
      - 'https://o0.pages.dev/mini/adblock.txt'
      - 'https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt'
      - 'https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt'
      - 'https://someonewhocares.org/hosts/zero/hosts'
      - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/ultimate.txt'
      - 'https://small.oisd.nl'
      - 'https://big.oisd.nl'
      - 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext'
      - 'https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts'
      - 'https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AdGuard%20Home%20Compilation%20List/AdGuardHomeCompilationList-Notifications.txt'
      - 'https://raw.githubusercontent.com/DandelionSprout/adfilt/master/GameConsoleAdblockList.txt'
      - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/whitelist-referral.txt'
      - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/anti.piracy.txt'
      - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/gambling.txt'
      - 'https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt'
      - 'https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt'
      - 'https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt'
      - 'https://anti-ad.net/easylist.txt'
      - 'https://raw.githubusercontent.com/hufilter/hufilter/master/hufilter-dns.txt'
      - 'https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/aghome.txt'
      - 'https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/PersianBlockerHosts.txt'
      - 'https://raw.githubusercontent.com/easylist/EasyListHebrew/master/hosts.txt'
      - 'https://raw.githubusercontent.com/cchevy/macedonian-pi-hole-blocklist/master/hosts.txt'
      - 'https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/NordicFiltersAdGuardHome.txt'
      - 'https://hole.cert.pl/domains/domains_adblock.txt'
      - 'https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/hostfile.txt'
      - 'https://raw.githubusercontent.com/lassekongo83/Frellwits-filter-lists/master/Frellwits-Swedish-Hosts-File.txt'
      - 'https://raw.githubusercontent.com/bkrucarci/turk-adlist/master/hosts'
      - 'https://raw.githubusercontent.com/symbuzzer/Turkish-Ad-Hosts/main/adguard/filter.txt'
      - 'https://abpvn.com/filter/abpvn-2N5Pga.txt'
      - 'https://malware-filter.gitlab.io/malware-filter/phishing-filter-agh.txt'
      - 'https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt'
      - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/tif.txt'
      - 'https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt'
      - 'https://phishing.army/download/phishing_army_blocklist_extended.txt'
      - 'https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt'
      - 'https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Malware'
      - 'https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts'
      - 'https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hosts'
      - 'https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt'
      - 'https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-agh.txt'
      - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.plus.txt'
      - 'https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-adguard.txt'
      - 'https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdns.txt'
      - 'https://johnshall.github.io/Shadowrocket-ADBlock-Rules-Forever/sr_ad_only.conf'
      - 'https://raw.githubusercontent.com/zsakvo/AdGuard-Custom-Rule/master/rule/zhihu-strict.txt'
      - 'https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt'
      - 'https://raw.githubusercontent.com/xndeye/adblock_list/main/rule/dns.txt'
      - 'https://raw.githubusercontent.com/adbyby/xwhyc-rules/master/lazy.txt'
      - 'https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad.txt'
      - 'https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad-edentw.txt'
      - 'https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad-pc.txt'
      - 'https://www.i-dont-care-about-cookies.eu/abp/'
      - 'https://gist.githubusercontent.com/Ewpratten/a25ae63a7200c02c850fede2f32453cf/raw/b9318009399b99e822515d388b8458557d828c37/hosts-yt-ads'
      - 'http://sub.adtchrome.com/adt-chinalist-easylist.txt'
      - 'https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts.txt'
      - 'https://raw.githubusercontent.com/jdlingyu/ad-wars/master/sha_ad_hosts'
      - 'https://neodev.team/adblocker'
      - 'https://fanboy.co.nz/r/fanboy-ultimate.txt'
      - 'http://mse.dl.360tpcdn.com/20210610/53b284ef5f4071a09d60d5f9f2a319fe.txt'
      - 'https://raw.githubusercontent.com/dajlelion/test/main/filters.txt'
      - 'https://abpvn.com/android/abpvn.txt'
      - 'https://easylist-downloads.adblockplus.org/easylistdutch.txt'
      - 'https://raw.githubusercontent.com/yous/YousList/master/hosts.txt'
      - 'https://raw.githubusercontent.com/DRSDavidSoft/additional-hosts/master/domains/blacklist/unwanted-iranian.txt'
      - 'https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/abpindo.txt'
      - 'https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-agh-online.txt'
      - 'https://cdn.jsdelivr.net/gh/privacy-protection-tools/anti-AD/anti-ad-easylist.txt'
      - 'http://sbc.io/hosts/alternates/fakenews-gambling-porn-social/hosts'
      - 'http://sbc.io/hosts/hosts'
      - 'https://raw.githubusercontent.com/vokins/yhosts/master/data/tvbox.txt'
      - 'https://adaway.org/hosts.txt'
      - 'https://raw.githubusercontent.com/8680/GOODBYEADS/master/rules.txt'
      - 'https://raw.githubusercontent.com/8680/GOODBYEADS/master/allow.txt'
      - 'https://easylist-downloads.adblockplus.org/easylistchina.txt'
      - 'https://easylist-downloads.adblockplus.org/easyprivacy.txt'
      - 'https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt'
      - 'https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad-mo.txt'
      - 'https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad2.txt'
      - 'https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad3.txt'
      - 'https://anti-ad.net/adguard.txt'
      - 'https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts'
      - 'https://raw.githubusercontent.com/Goooler/1024_hosts/master/hosts'
      - 'https://abp.oisd.nl/basic/'
      - 'https://raw.githubusercontent.com/neodevpro/neodevhost/master/lite_adblocker'
      - 'https://hblock.molinero.dev/hosts_adblock.txt'
      - 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt'
      - 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt'
      - 'https://easylist-downloads.adblockplus.org/easylist.txt'
      - 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt'
      - 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_224_Chinese/filter.txt'


    #本地规则
    # local: #本地规则请将文件移动到项目路径rule目录中
    #   - 'mylist.txt'
  output:
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt:    #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      adgh.txt:
        - DOMAIN
        - REGEX
#        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
